modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/Hellish-Mods/KesseractJS/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs"
version = "${version}"
displayName = "KesseractJS"
authors = "LatvianModder, ZZZank, Hellish Mods (G_cat), MundM2007"
description = '''
A maintained fork of the 1.16.5 version of KubeJS
'''
logoFile = "pack.png"
license = "GNU LGPLv3"

[[dependencies.kubejs]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs]]
modId = "rhizo"
mandatory = true
versionRange = "[3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "gamestages"
mandatory = false
versionRange = "[${gamestages_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs]]
modId = "jei"
mandatory = false
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"